### ISSUE TITLE
Unable to open solutions in UCERF3 faults plugin

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/scec-vdo#2]
Since https://github.com/GNS-Science/scec-vdo/pull/1 we can no longer open solutions. (However rupture sets seem OK)

example (opening ./nshm-nz-opensha/data/inversionSolutions/TestSolution_185m_CRUSTAL_SANS_TVZ2_BGSEIS_thin0.0.zip

```
log4j:WARN No appenders could be found for logger (org.scec.vtk.tools.plugins.Plugins).
log4j:WARN Please initialize the log4j system properly.
****************ADDED PLUGIN: Political Boundaries
/home/chrisbc/DEV/GNS/opensha/scec-vdo/data/Grid/California.grat
****************ADDED PLUGIN: Graticule
****************ADDED PLUGIN: Drawing Tools
LayerID: org.scec.vdo.politicalBoundaries
LayerID: org.scec.vdo.graticulePlugin
LayerID: org.scec.vdo.drawingToolsPlugin
pluginLayerid: org.scec.vdo.politicalBoundaries should be equivalent to: org.scec.vdo.politicalBoundaries
pluginLayerid: org.scec.vdo.graticulePlugin should be equivalent to: org.scec.vdo.graticulePlugin
pluginLayerid: org.scec.vdo.drawingToolsPlugin should be equivalent to: org.scec.vdo.drawingToolsPlugin
/home/chrisbc/DEV/GNS/opensha/scec-vdo/data ? true
****************ADDED PLUGIN: UCERF3 Fault System Ruptures Plugin
java.lang.NullPointerException
	at scratch.UCERF3.FaultSystemRupSet.getNumRuptures(FaultSystemRupSet.java:218)
	at scratch.UCERF3.FaultSystemRupSet.setClusterRuptures(FaultSystemRupSet.java:836)
	at scratch.UCERF3.inversion.InversionFaultSystemRupSet.<init>(InversionFaultSystemRupSet.java:222)
	at scratch.UCERF3.utils.FaultSystemIO.loadRupSetAsApplicable(FaultSystemIO.java:471)
```

**Comment by chrisbc** [comment]
NB this looks like it might be the same issue we fixed a little while ago in public class InversionFaultSystemRupSet where init needed to be called in proper sequence (around line 225 - 228). IN this case getNumRuptures would raise NullPointer because mags[] was not yet set.

I can't see where how the **opensha.jar** is built for scec-vdo. Is it possible that this needs to be updated??

**Comment by chrisbc** [comment]
moved this issue to the upstream project for Kevin
